### PR TITLE
Respec Fixes

### PR DESCRIPTION
**Pull request by halindrome**
Fixed ReSpec processing issues.  I think there was just a JS syntax error.

Also added daniel and shane as editors.

@burnburn r?

### CODE REVIEW

**Comment by burnburn** [comment]
@halindrome,  github diff only shows two changes:  the edDraftURI and the editors.  I don't see any ReSpec fixes.

**Comment by halindrome** [comment]
Yeah you're right.  No idea what happened there.  I am going to close this PR and do it harder later.  But I have meetings now.

**Comment by burnburn** [comment]
BTW, I started with data-lt and tried changing to lt based on https://www.w3.org/respec/guide.html where it shows both, but neither one seemed to be able to deal with the fact that I wanted to define multiple id attributes in different webidl sections with different data-lt values to distinguish them.  If necessary there is a longer syntax I can use once the IDL is fine that explicitly references specific subsets of the idl, but the idl has to be valid first.

**Comment by halindrome** [comment]
WebIDL continuous does it automatically...  It assigns scoped IDs based upon the interface name or whatever.

**Comment by burnburn** [comment]
Yes, exactly.

**Comment by halindrome** [comment]
Sorry I got sucked into meetings for 6 hours yesterday.  I will get back on
this today.

On Wed, May 11, 2016 at 8:29 AM, Daniel Burnett notifications@github.com
wrote:

> Yes, exactly.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/opencreds/website/pull/64#issuecomment-218459123

## 

Shane McCarron
halindrome@gmail.com

**Pull request closed without merging**
